### ISSUE TITLE
Using StaticModuleRecord with Typescript and Jest

### ISSUE THREAD

**Issue by ClemensLey** [endojs/endo#1179]
I am trying to create a StaticModuleRecord using Typescript in a jest test case but I'm getting this error:

````
    TypeError: Cannot read properties of undefined (reading 'identifier')

      14 |     }`
      15 |
    > 16 |     const record = new StaticModuleRecord(cls)
         |                    ^
      17 |     expect(record).toBeDefined()
      18 |   })
      19 | })

      at hiddenIdentifier (node_modules/@endo/static-module-record/src/babelPlugin.js:95:23)
      at node_modules/@endo/static-module-record/src/babelPlugin.js:99:21
      at visitorFromPlugin (node_modules/@endo/static-module-record/src/transform-analyze.js:15:37)
      at transformSource (node_modules/@endo/static-module-record/src/transform-analyze.js:33:24)
      at createStaticRecord (node_modules/@endo/static-module-record/src/transform-analyze.js:73:26)
      at node_modules/@endo/static-module-record/src/transform-analyze.js:139:31
      at new StaticModuleRecord (node_modules/@endo/static-module-record/src/static-module-record.js:54:7)
      at Object.<anonymous> (test.ts:16:20)
````

It works fine in node using the ``--loader ts-node/esm`` flag but I do not know how to get it to work in jest. I pushed the code to a [repo](https://github.com/bitcoin-computer/ses-test). To reproduce

````
git clone https://github.com/bitcoin-computer/ses-test.git
cd ses-test
yarn install

// log a StaticModuleRecord in node, this works fine
yarn start 

// // created a StaticModuleRecord in a jest test, this produces the error
yarn test 
````

Most of my setup is taken from [here](https://github.com/jason-henriksen/typescript-with-esm-no-babel-boilerplate):

**package.json**

````
{
  "name": "ses-test",
  "version": "1.0.0",
  "main": "index.js",
  "repository": "https://github.com/bitcoin-computer/ses-test.git",
  "author": "Clemens Ley <ley.clemens@gmail.com>",
  "license": "MIT",
  "type": "module",
  "scripts": {
    "start": "node --loader ts-node/esm index.ts",
    "test": "jest --config ./jest.config.json"
  },
  "dependencies": {
    "@endo/static-module-record": "^0.7.4",
    "@types/jest": "^27.5.0",
    "jest": "^28.0.3",
    "ses": "^0.15.15",
    "ts-jest": "^28.0.0",
    "ts-lib": "^0.0.5",
    "ts-node": "^10.7.0",
    "tslib": "^2.4.0",
    "typescript": "^4.6.4"
  },
  "devDependencies": {
    "@types/node": "^17.0.31"
  }
}
````

**jest.config.json**
````
{
  "globals": {
    "extensionsToTreatAsEsm": [
      ".ts",
      ".js"
    ],
    "ts-jest": {
      "useESM": true
    }
  },
  "preset": "ts-jest/presets/js-with-ts-esm",
  "transformIgnorePatterns": [],
  "testPathIgnorePatterns": [
    "/node_modules/",
    "dist"
  ]
}
````

**tsconfig.json**

````
{
  "compilerOptions": {
    // This was actually kind of a nightmare to figure out.
    // There is a LOT of outdated, incorrect advise out there.
    // there is/was an ESM vs CommonJS war that's made a huge mess, this seems to get us through it.
    "target": "esnext", // DO NOT CHANGE!
    "module": "esnext", // DO NOT CHANGE!
    "moduleResolution": "node",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": true,
    "strict": true,
    "noImplicitAny": true /* Raise error on expressions and declarations with an implied 'any' type. */,
    "strictNullChecks": true /* Enable strict null checks. */,
    "strictFunctionTypes": true /* Enable strict checking of function types. */,
    "noUnusedLocals": true /* Report errors on unused locals. */,
    "noUnusedParameters": true /* Report errors on unused parameters. */,
    "noImplicitReturns": true /* Report error when not all code paths in function return a value. */,
    "noFallthroughCasesInSwitch": true /* Report errors for fallthrough cases in switch statement. */,
    "importHelpers": true,
    "skipLibCheck": true,
    "outDir": "./dist/tsc/",
    "types": [
      "node",
      "jest"
    ],
    "lib": [
      "ES6",
      "DOM"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
  ],
  "exclude": [
    "node_modules",
    ".vscode"
  ]
}
````

**Comment by ClemensLey** [comment]
It turns out that testing the static module record works out of the box in mocha and ava. We will be using mocha going forward, so there is no urgency from our side to add support for jest.

Thanks for the great work on SES.

**Comment by mhofman** [comment]
@ClemensLey, sorry for not answering you timely. Unfortunately Jest sets up an environment which is simply incompatible with SES. That's because it creates a Realm through the `vm` module, but brings in a ton of intrinsics from the incubator/main realm, creating a Frankenstein environment that is simply impossible to secure.

Some day I'd like to create a SES environment plugin for Jest that skips all the cruft that the default vm based env creates and uses SES compartments to safely evaluate test code, but that's a long term project.

As you found out, ava works fine with SES. You may want to use a wrapped `test`, e.g. from https://github.com/endojs/endo/blob/master/packages/import-bundle/test/prepare-test-env-ava.js

Some context:
- https://github.com/facebook/jest/issues/11952
- https://github.com/Agoric/agoric-sdk/issues/3918
- https://github.com/facebook/jest/issues/2549

**Comment by ClemensLey** [comment]
Cool, thanks for letting me know Mathieu.
