### ISSUE TITLE
Assign to Function.toString success but it shouldn't

### ISSUE THREAD

**Issue by Jack-Works** [endojs/endo#1227]
![image](https://user-images.githubusercontent.com/5390719/176100694-5eec816d-14d3-4f18-b4e9-398404944a69.png)

**Comment by kriskowal** [comment]
Thanks again for posting @Jack-Works. I’m reviewing stale issues. This one appears to be fixed.

```js
import 'ses';
lockdown();
Function.toString = 1;
```

```
(TypeError#1)
TypeError#1: Cannot define property toString, object is not extensible

  at defineProperty (<anonymous>)
  at defineProperty (packages/ses/src/commons.js:101:18)
  at Function.setter (packages/ses/src/enable-property-overrides.js:118:11)
  at packages/ses/temp.js:3:19
```
