### ISSUE TITLE
MetaMask build process fails with EndoJS based tool LavaMoat

### ISSUE THREAD

**Issue by weizman** [endojs/endo#1358]
`lockdown.umd` moving some `console.log`s to `console.warn`s seems to cause the MM build system which uses LavaMoat which uses EndoJS to crash @rekmarks @kriskowal 

## Reproduce

```
git clone https://github.com/weizman/metamask-extension.git
cd metamask-extension
git checkout endojs-issue-1358-demo
yarn setup
yarn lavamoat:build:auto
yarn dist
```

(or copy `mkdir issue-1358 && cd issue-1358 && git clone https://github.com/weizman/metamask-extension.git && cd metamask-extension && git checkout endojs-issue-1358-demo && yarn setup && yarn lavamoat:build:auto && yarn dist`)

## Expected

Build should work smoothly

## Result

Max stack errors are thrown

## Notes

When you modify `warn` back to `log` everything goes back to work normally

* https://github.com/weizman/metamask-extension/blob/endojs-issue-1358-demo/patches/lavamoat-core+12.3.0.patch#L10
* https://github.com/weizman/metamask-extension/blob/endojs-issue-1358-demo/patches/lavamoat-core+12.3.0.patch#L20

If you want to update the value of `Error.stackTraceLimit` do so at the beginning of `/metamask-extension/node_modules/lavamoat-core/lib/lockdown.umd.js`

**Comment by weizman** [comment]
`Error.stackTraceLimit = 50;`

```
RangeError: Maximum call stack size exceeded
  at performEval (LavaMoat/node/kernel:4154:27)
  at compartmentEvaluate (LavaMoat/node/kernel:4276:10)
  at Compartment.evaluate (LavaMoat/node/kernel:7121:12)
  at prepareModuleInitializer (LavaMoat/core/kernel:665:42)
  at internalRequire (LavaMoat/core/kernel:518:50)
  at requireRelative (LavaMoat/core/kernel:575:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:544:18)
  at tryNpmPath (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/Users/weizman/Documents/weizman/temp/endo1358/3/metamask-extension/node_modules/global-prefix/index.js:84:12)
```

**Comment by weizman** [comment]
`Error.stackTraceLimit = 50;`

```
RangeError: Maximum call stack size exceeded
  at performEval (LavaMoat/node/kernel:4154:27)
  at compartmentEvaluate (LavaMoat/node/kernel:4276:10)
  at Compartment.evaluate (LavaMoat/node/kernel:7121:12)
  at prepareModuleInitializer (LavaMoat/core/kernel:665:42)
  at internalRequire (LavaMoat/core/kernel:518:50)
  at requireRelative (LavaMoat/core/kernel:575:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:544:18)
  at tryNpmPath (/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/metamask-extension/node_modules/global-prefix/index.js:84:12)
  at requireRelativeWithContext (LavaMoat/core/kernel:540:49)
  at tryNpmPath (/metamask-extension/node_modules/global-prefix/index.js:68:28)
  at getPrefix (/metamask-extension/node_modules/global-prefix/index.js:34:13)
  at Object.get [as exports] (/metamask-extension/node_modules/global-prefix/index.js:84:12)
```

**Comment by weizman** [comment]
Hard to tell at this point. 
We just updated SES over at LavaMoat https://github.com/LavaMoat/LavaMoat/pull/394 and we're encountering more issues around it (LavaMoat tests work, but MetaMask build process which is based on LavaMoat fails since the update).
Might be related, might not, I'll dig dipper and hopefully be able to tell soon.
