### ISSUE TITLE
App scaffolded with create-cosmos-app cannot call lockdown successfully

### ISSUE THREAD

**Issue by samsiegart** [endojs/endo#2033]
## Describe the bug

As shown in https://github.com/agoric-labs/hardened-create-cosmos-app, when I try using `create-cosmos-app` to make a cosmos app (which runs on Next.js), I cannot successfully invoke `lockdown` and run the app. See the README of that repo for error details.

## Steps to reproduce

1. Clone https://github.com/agoric-labs/hardened-create-cosmos-app
2. `yarn && yarn dev` to install deps and run locally
3. Load the url outputted by `yarn dev`
4. Observe the error

## Expected behavior

`lockdown` can be invoked in the top-level of the application without error.

## Platform environment

- What OS are you using? MacOS 13.3.1 (22E261)
- What version of Node.js? v18.17.1
- Is there anything special/unusual about your platform? No
- What version of Endo are you using? "ses": "^1.1.0"

## Additional context

Create-cosmos-app is a tool for scaffolding cosmos apps with Next.js. It would be beneficial to be able to use SES and Endo APIs in apps built using this tool. The error is perhaps more general to Next.js as a whole, but this tool is of particular interest.

## Screenshots

See https://github.com/agoric-labs/hardened-create-cosmos-app

**Comment by kriskowal** [comment]
This smells like a CommonJS interop issue and I would like to summon @naugtur, if we can borrow his eyes.

**Comment by kriskowal** [comment]
@samsiegart Capturing the error in the description will help us diagnose.

**Comment by samsiegart** [comment]
> @samsiegart Capturing the error in the description will help us diagnose.

There's a screenshot and two stack traces in the example repo's [README](https://github.com/agoric-labs/hardened-create-cosmos-app?tab=readme-ov-file#overview). I've updated the description here to point it out more explicitly

**Comment by samsiegart** [comment]
Oh, it's private, I should make it public

**Comment by erights** [comment]
@kriskowal , I've assigned it to the two of us.

**Comment by erights** [comment]
@naugtur , you too ;)

**Comment by LuqiPan** [comment]
Another data point- shouldn't be a surprise given I'm using the same `create-cosmos-app`, just with a slightly different template:
I tried to initialize an NFT example with `create-cosmos-app --name hardened-nft-example --example nft` and I got the same error as @samsiegart, see https://github.com/agoric-labs/hardened-nft-example?tab=readme-ov-file#bug-report

**Comment by erights** [comment]
Reproduced locally! Thanks for the clear and simple instructions.

**Comment by erights** [comment]
Yeah, @naugtur @kriskowal , it is all about the cjs loader. I will definitely need your help looking at this. It was easy to reproduce locally, so could you have a look? If the bug is interesting, perhaps we could discuss it at the upcoming endo meeting?

**Comment by erights** [comment]
Actually, this seems kinda urgent for us. Could we meet tomorrow after you've taken a first look? I am free tomorrow anytime after 2pm Pacific.

**Comment by kumavis** [comment]
@tgrecojs you mentioned on the call you might be familiar with this issue

**Comment by tgrecojs** [comment]
I just took a moment to spin up an example repo which integrates `@endo/init` into a next.js application. This code can be found here - https://github.com/tgrecojs/nextjs-with-endo-init

Pasting the contents of the README file from that repository below. @samsiegart let me know if this helps as all. One more thing I want to note - I think your repo may be using a version of past next.js. FWIW I have wired up past versions to work with endo so I don't *believe* that is the issue here but I'm not entirely sure.

# README.md

## Next.js X @endo/init

> View this incredibly rich and interactive demo here - https://hardened-nextjs-repo.vercel.app/.

This repository demonstrates the integration of Endo and Knit within a Next.js application. 

Below you can view contents of the project's [_document.js](./pages/_document.js) file. 
```js
import { Html, Head, Main, NextScript } from "next/document";
import Script from "next/script";

export default function Document() {
  return (
    <Html>
      <Head />
      <body>
        <Main />
        <NextScript />
        <Script
          async
          type="module"
          src="https://esm.sh/@endo/init@1.0.2"
          strategy="beforeInteractive"
        />
      </body>
    </Html>
  );
}
```

The key component within this file is the [Next.js specific <Script /> element](https://nextjs.org/docs/pages/api-reference/components/script) as it is responsible for loading `@endo/init`. When used outside of Next.js' `_document.js` file, this component has been the source of issues when loading the page such as the one seen [here](https://github.com/agoric-labs/hardened-create-cosmos-app?tab=readme-ov-file#overview) (although it is not necessarily responsible for this issue).

### Checking for tamper-proof globals.

Below is a screenshot of interaction from [https://hardened-nextjs-repo.vercel.app](https://hardened-nextjs-repo.vercel.app/)

![ss_02142024_000144](https://github.com/tgrecojs/nextjs-with-endo-init/assets/6646552/e9fb8539-4e1d-4465-8d44-9962aa18f787)

**Comment by naugtur** [comment]
I reproduced the error and the error starts on the server
```
$ next dev
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000

 ✓ Ready in 1626ms
 ✓ Compiled / in 1937ms (2269 modules)
 ⨯ [ReferenceError: __webpack_require__ is not defined
  at Object.eval (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES&page=%2F&preferredRegion=&absolutePagePath=.%2Fpages%2Findex.tsx&absoluteAppPath=private-next-pages%2F_app&absoluteDocumentPath=private-next-pages%2F_document&middlewareConfigBase64=e30%3D!:1:1)
  at eval (eval at makeEvaluate (file:///lab/samples/hardened-create-cosmos-app/node_modules/ses/src/make-evaluate.js:92:27), <anonymous>:12:22)
  at ./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES&page=%2F&preferredRegion=&absolutePagePath=.%2Fpages%2Findex.tsx&absoluteAppPath=private-next-pages%2F_app&absoluteDocumentPath=private-next-pages%2F_document&middlewareConfigBase64=e30%3D! (/lab/samples/hardened-create-cosmos-app/.next/server/pages/index.js:22:1)
  at __webpack_require__ (/lab/samples/hardened-create-cosmos-app/.next/server/webpack-runtime.js:33:42)
  at __webpack_exec__ (/lab/samples/hardened-create-cosmos-app/.next/server/pages/index.js:361:39)
  at /lab/samples/hardened-create-cosmos-app/.next/server/pages/index.js:362:114
  at __webpack_require__.X (/lab/samples/hardened-create-cosmos-app/.next/server/webpack-runtime.js:185:21)
  at /lab/samples/hardened-create-cosmos-app/.next/server/pages/index.js:362:47
  at Object.<anonymous> (/lab/samples/hardened-create-cosmos-app/.next/server/pages/index.js:365:3)] {
  page: '/'
}
 ✓ Compiled /_error in 228ms (2271 modules)
[ReferenceError: exports is not defined
  at Object.eval (webpack-internal:///./node_modules/next/dist/pages/_document.js:2:23)
  at eval (eval at makeEvaluate (file:///lab/samples/hardened-create-cosmos-app/node_modules/ses/src/make-evaluate.js:92:27), <anonymous>:12:22)
  at ./node_modules/next/dist/pages/_document.js (/lab/samples/hardened-create-cosmos-app/.next/server/vendor-chunks/next.js:30:1)
  at __webpack_require__ (/lab/samples/hardened-create-cosmos-app/.next/server/webpack-runtime.js:33:42)
  at __webpack_exec__ (/lab/samples/hardened-create-cosmos-app/.next/server/pages/_document.js:52:39)
  at /lab/samples/hardened-create-cosmos-app/.next/server/pages/_document.js:53:83
  at __webpack_require__.X (/lab/samples/hardened-create-cosmos-app/.next/server/webpack-runtime.js:185:21)
  at /lab/samples/hardened-create-cosmos-app/.next/server/pages/_document.js:53:47
  at Object.<anonymous> (/lab/samples/hardened-create-cosmos-app/.next/server/pages/_document.js:56:3)]

```

**Comment by naugtur** [comment]
@tgrecojs The difference between yours and this repo seems to be this one is running lockdown on the serverside and yours is running it on clientside.
1. What is the intended result?
2. re your way of adding it to the clientside - this reminds me of a similar situation in our work on lockdown for react native where we were trying to find the right place to run it. Are you sure this way you're not running lockdown too late?

**Comment by tgrecojs** [comment]
I'm getting the impression that you may have viewed the repo I spun up as a potential solution to the issues your facing with create-cosmos-app. I want to quickly clarify that this was not my intention at all. It was only meant to provide some added context into integrating next.js with SES.

So, as for your ask...

> It would also be preferred to be able to load `ses` from a local bundle as opposed to the url `https://esm.sh/@endo/init@1.0.2`

I can reference @endo/init locally without issue. But is that the only ask here, or am I missing something. If it's not, then please let me know what your end goal is so I can try and assist.

**Comment by samsiegart** [comment]
Yea the intended result is that we can use endo APIs inside the application on top of next.js+create-cosmos-app. I guess if the local `@endo/init` is a non-factor, then we're just on the question of whether we need `beforeInteractive` or not. I can try based on your example and see if it works to call [`makeAgoricWalletConnection`](https://github.com/Agoric/ui-kit/blob/main/packages/web-components/src/wallet-connection/walletConnection.js) without `beforeInteractive`. If so your `<Script>` tag solution could suffice.

**Comment by gacogo** [comment]
I came across this when trying to fork [dapp-offer-up](https://github.com/Agoric/dapp-offer-up). I went around it by  [disabling server side rendering](https://github.com/gacogo/dapp-offer-up/blob/gacogo/dapp-offer-up-next/next-ui/src/app/%5B%5B...slug%5D%5D/client.tsx#L5). 

demo: https://dapp-offer-up-next-ui.vercel.app/

**Comment by tgrecojs** [comment]
The goal here seems to be using next.js' SSR capabilities and from what i've gathered the Script tag is the vehicle that will get us to the desired outcome. I've just drafted a PR for this [here.](https://github.com/agoric-labs/hardened-create-cosmos-app/pull/1). I'm adding the comments from that here for visibility.

> I'm not completely over the hill yet but I think there is some solid progress made. For one, i'm almost certain that the approach that needs to be taken is to use `beforeInteractive` with _document.js. This change makes use of this approach, and everything seems to render properly. There is only one issue - @endo/init doesn't seem to be doing anything? 

> Below is a screen grab of the application booting up. You can see that @endo/init is the first script loaded out of the bunch, which is the expected behavior of `beforeInteractive`. But it doesn't seem to actually be calling lockdown. 

https://github.com/agoric-labs/hardened-create-cosmos-app/assets/6646552/5e213ddf-5a15-4814-91bb-0849a8bd16f5


> Here is the URL for this deployment - https://create-cosmos-app-three.vercel.app/.

@endo/init seems to be getting imported, but it just stops there resulting in `Object.isFrozen(Array.prototype)` returns false.

I'm wondering if anyone can give additional input on how @endo/init is functioning here. I'm not sure why `lockdown` doesn't seem to be getting called? And how can I make sure the `@endo/init` invokes lockdown (I expected it to invoke `lockdown` automatically). 

It seems like there is something I'm missing here but not exactly sure what 🤔 cc @naugtur @kriskowal @kumavis

**Comment by gacogo** [comment]
Hey @samsiegart . I've created  a [pull reques](https://github.com/agoric-labs/hardened-create-cosmos-app/pull/2)t intended to fix these issues, using a slightly modified `installSesLockdown.ts`.  I hope you find it helpful.

**Comment by tgrecojs** [comment]
@gacogo this is a really interesting solution! I do have one question - are you still disabling SSR in your PR?

Also, i'm not sure if you read any of my comments on this issue but I provide a fairly detailed look into how next.js suggests loading scripts (without disabling SSR).

**Comment by gacogo** [comment]
@tgrecojs Am not disabling ssr with this solution. I also tried dynamic imports with `{ssr: true}` and it worked.

**Comment by erights** [comment]
What's the status of this? Should this be tracked as an endo ecosystem compat issue https://github.com/endojs/endo/issues/2037 ?

**Comment by RicFer01** [comment]
@gacogo  I tried to use you solution with:

```
(async () => {
  await import("ses"); // adds lockdown, harden, and Compartment
  const consoleTaming = process.env.NEXT_PUBLIC_CONSOLE_TAMING  ? 'unsafe' : 'safe';

  lockdown({
    errorTaming: "unsafe",
    overrideTaming: "severe",
    consoleTaming,
  });

  Error.stackTraceLimit = Infinity;

})();

export default function initiateLockdown() {
  return Promise.resolve();
}
```

But I still get the error:
```
[SyntaxError: Possible import expression rejected at [module]:32. (SES_IMPORT_REJECTED)
  at rejectImportExpressions (webpack-internal:///(rsc)/./node_modules/ses/src/transforms.js:155:65)
  at mandatoryTransforms (webpack-internal:///(rsc)/./node_modules/ses/src/transforms.js:243:12)
  at applyTransforms (webpack-internal:///(rsc)/./node_modules/ses/src/transforms.js:257:14)
...
```

does it work for you now?
