### ISSUE TITLE
possible flake: test loopback gc

### ISSUE THREAD

**Issue by erights** [endojs/endo#2634]
As seen at https://github.com/endojs/endo/actions/runs/11874583594/job/33090758261?pr=1538#step:7:72

Suspected as a flake because it succeeds on Node 18.x and 22.4.1 but fails on Node 20.x

![image](https://github.com/user-attachments/assets/c2a05611-6594-443b-a1db-1e95eba4a902)

```
 ✘ [fail]: gc › test loopback gc
    ℹ REJECTED from ava test("test loopback gc"): (TestFailure#1)
    ℹ TestFailure#1: The test has failed
    ℹ     at Test.saveFirstError (file:///home/runner/work/endo/endo/node_modules/ava/lib/test.js:410:22)
          at Test.addFailedAssertion (file:///home/runner/work/endo/endo/node_modules/ava/lib/test.js:358:8)
          at fail (file:///home/runner/work/endo/endo/node_modules/ava/lib/test.js:50:17)
          at ExecutionContext.like (file:///home/runner/work/endo/endo/node_modules/ava/lib/assert.js:391:10)
          at Object.value [as like] (file:///home/runner/work/endo/endo/packages/ses-ava/src/ses-ava-test.js:165:35)
          at file:///home/runner/work/endo/endo/packages/captp/test/gc.test.js:32:5

  ✔ trap › try restricted loopback trap
  ✔ trap › try Node.js worker trap, main guest (171ms)
  ✔ trap › try Node.js worker trap, main host (190ms)
  ✔ loopback › try loopback captp (217ms)
  ─

  gc › test loopback gc
  test/gc.test.js:32

   31:   const farStats = getFarStats();
   32:   t.like(                        
   33:     { nearStats, farStats },     

  Difference (- actual, + expected):

    {
      farStats: {
        gc: {
  -       DROPPED: 3,
  +       DROPPED: 4,
        },
        recv: {
  -       CTP_DROP: 3,
  +       CTP_DROP: 4,
        },
        send: {
          CTP_DROP: 2,
        },
      },
      nearStats: {
        gc: {
          DROPPED: 2,
        },
        recv: {
          CTP_DROP: 2,
        },
        send: {
  -       CTP_DROP: 3,
  +       CTP_DROP: 4,
        },
      },
    }

  › Object.value [as like] (file:///home/runner/work/endo/endo/packages/ses-ava/src/ses-ava-test.js:165:35)
  › file://test/gc.test.js:32:5
```

**Comment by erights** [comment]
Update: confirmed as a flake. Didn't fail on reexecution
