### ISSUE TITLE
bare Error instance does not log correctly

### ISSUE THREAD

**Issue by kumavis** [endojs/endo#944]
ses: (`master` at time of writing [ac1cc0](https://github.com/endojs/endo/tree/ac1cc06f3665c94ace2f551a07072cc094706a62)) 
node: v14.17.6 
```js
require('ses/lockdown');
lockdown({ errorTaming: 'unsafe', stackFiltering: 'verbose', consoleTaming: 'unsafe', domainTaming: 'unsafe' })
console.error(new Error('boom'));
```

logs only
```
{}
```

error stack and message are intact

**Comment by kumavis** [comment]
with `overideTaming: 'min'`
```
[Error: boom
  at file:///home/xyz/Development/endo/packages/ses/abc.js:10:13
  at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
  at async Loader.import (internal/modules/esm/loader.js:178:24)
  at async Object.loadESM (internal/process/esm_loader.js:68:5)]
```

with `overideTaming: 'moderate'`**(default)**
```
{}
```

with `overideTaming: 'severe'`
```
[Error <Object <[Object: null prototype] {}>>: boom
  at file:///home/xyz/Development/endo/packages/ses/abc.js:10:13
  at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
  at async Loader.import (internal/modules/esm/loader.js:178:24)
  at async Object.loadESM (internal/process/esm_loader.js:68:5)]
```

**Comment by kumavis** [comment]
```js
lockdown({ overrideTaming, errorTaming: 'unsafe', stackFiltering: 'verbose', consoleTaming: 'unsafe' });
console.log(Object.getOwnPropertyDescriptors(Error.prototype));
```


- min:
```
{
  constructor: {
    value: [Function: Error],
    writable: false,
    enumerable: false,
    configurable: false
  },
  name: {
    get: [Function: getter],
    set: [Function: setter],
    enumerable: false,
    configurable: false
  },
  message: {
    value: '',
    writable: false,
    enumerable: false,
    configurable: false
  },
  toString: {
    value: [Function: toString],
    writable: false,
    enumerable: false,
    configurable: false
  }
}
```

- moderate (default):
```
{
  constructor: { get: {}, set: {}, enumerable: false, configurable: false },
  name: { get: {}, set: {}, enumerable: false, configurable: false },
  message: { get: {}, set: {}, enumerable: false, configurable: false },
  toString: { get: {}, set: {}, enumerable: false, configurable: false }
}
```

- severe:
```
Object <[Object: null prototype] {}> {
  constructor: Object <[Object: null prototype] {}> {
    get: [Function: getter] Function <Function <Complex prototype>>,
    set: [Function: setter] Function <Function <Complex prototype>>,
    enumerable: false,
    configurable: false
  },
  name: Object <[Object: null prototype] {}> {
    get: [Function: getter] Function <Function <Complex prototype>>,
    set: [Function: setter] Function <Function <Complex prototype>>,
    enumerable: false,
    configurable: false
  },
  message: Object <[Object: null prototype] {}> {
    get: [Function: getter] Function <Function <Complex prototype>>,
    set: [Function: setter] Function <Function <Complex prototype>>,
    enumerable: false,
    configurable: false
  },
  toString: Object <[Object: null prototype] {}> {
    get: [Function: getter] Function <Function <Complex prototype>>,
    set: [Function: setter] Function <Function <Complex prototype>>,
    enumerable: false,
    configurable: false
  }
}
```

**Comment by kumavis** [comment]
'%ErrorPrototype%': { constructor: true } breaks the logging of errors
'%ObjectPrototype%': { 'constructor': true, } re-fixes the logging of errors

**Comment by kumavis** [comment]
https://github.com/nodejs/node/blob/7633c86eebbf6e381e60e63dc6e3eb36a3cce276/lib/internal/util/inspect.js#L286
https://github.com/nodejs/node/blob/7633c86eebbf6e381e60e63dc6e3eb36a3cce276/lib/internal/util/inspect.js#L726
https://github.com/nodejs/node/blob/7633c86eebbf6e381e60e63dc6e3eb36a3cce276/lib/internal/util/inspect.js#L796
https://github.com/nodejs/node/blob/7633c86eebbf6e381e60e63dc6e3eb36a3cce276/lib/internal/util/inspect.js#L554
why `constructor` as getter is problematic ^

**Comment by kumavis** [comment]
this api may allow us to customize and fix output https://github.com/nodejs/node/blob/7633c86eebbf6e381e60e63dc6e3eb36a3cce276/lib/internal/util/inspect.js#L294-L304

**Comment by kumavis** [comment]
neat hack, if you add a `constructor` property on the `Error` instance, it will log correctly in node

```js
Object.defineProperty(err, 'constructor', { value: Error })
```

**Comment by erights** [comment]
See #636

**Comment by erights** [comment]
Do you have a reason to turn on `consoleTaming: 'unsafe'`? Without it, do you see error stacks?

**Comment by kumavis** [comment]
see log in https://github.com/kolbytn/mindcraft/issues/359
ses configuration https://github.com/kolbytn/mindcraft/blob/5c3efb870ba340e814cfc031829b7f0d71dae07f/src/agent/library/lockdown.js#L7-L16

**Comment by erights** [comment]
See https://github.com/endojs/endo/issues/2908

**Comment by erights** [comment]
@kumavis , what are the current symptoms? Has this bug been fixed?

**Comment by erights** [comment]
What about on a Node after https://github.com/nodejs/node/pull/59456 was merged?
