### ISSUE TITLE
agoric-sdk master fails on ses from endo master

### ISSUE THREAD

**Issue by erights** [endojs/endo#962]
When I try `yarn test` on a fresh agoric-sdk locally, it completes fine. But if I link it against the current master of ses from endo master, then `yarn test` fails in SwingSet as follows:

```
error Error: syscall.retireExports failed, prepare to die: syscall translation error: prepare to die during vat dispatch() of bringOutYourDead
delivery problem, terminating vat v2 syscall.retireExports failed, prepare to die: syscall translation error: prepare to die
error during syscall translation: (Error#58)
Error#58: vref o+1 not in clist
  at mapVatSlotToKernelSlot (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:239:7)
  at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:306:20)
  at Array.map (<anonymous>)
  at translateRetireExports (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:301:25)
  at Object.vatSyscallToKernelSyscall (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:398:16)
  at vatSyscallHandler (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:894:27)
  at syscallFromWorker (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:251:18)
  at doSyscall (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:72:11)
  at Object.retireExports (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:109:31)
  at scanForDeadObjects (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:287:15)
  at runMicrotasks (<anonymous>)
  at async bringOutYourDead (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:1197:20)
  at async Object.deliver (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:157:20)
  at async Object.deliverToVat (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:278:28)
  at async deliverAndLogToVat (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:436:30)
  at async processBringOutYourDead (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:682:19)
  at async processQueueMessage (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:801:23)
  at async Object.run (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/dist/ses.umd.js:1400:10)), <anonymous>:1181:27)
  at async doTerminate (packages/SwingSet/test/vat-admin/terminate/test-terminate.js:32:3)
  at async packages/SwingSet/test/vat-admin/terminate/test-terminate.js:58:3

error Error: syscall.retireExports failed, prepare to die: syscall translation error: prepare to die during vat dispatch() of bringOutYourDead
delivery problem, terminating vat v2 syscall.retireExports failed, prepare to die: syscall translation error: prepare to die
  vat-warehouse › reload-snapshot › vat reload from snapshot

  Rejected promise returned by test. Reason:

  ExitCode (ErrorCode) @Error {
    code: 2,
    message: 'v1:target exited: I/O error',
  }

  › new ErrorCode (packages/xsnap/api.js:49:5)
  › ChildProcess.<anonymous> (packages/xsnap/src/xsnap.js:124:22)

  ─

  1 test failed
  12 known failures
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by erights** [comment]
See also https://github.com/Agoric/agoric-sdk/issues/4189

I'm reporting it to both repositories because I have no idea which one needs fixing.

**Comment by kriskowal** [comment]
“v1:target exited: I/O error” is known to be broken on Agoric SDK master per https://github.com/Agoric/agoric-sdk/pull/4167, which is a WIP branch attempting to synchronize the versions in the Endo repository with those in Agoric SDK. XS is dying while attempting to snapshot under a number of tests. This is a regression caused by syncing Endo, but not clearly due to a fault in any of the Endo projects. Likely an existing bug in XS.

**Comment by Tartuffo** [comment]
@erights Still an issue?

**Comment by erights** [comment]
> @erights Still an issue?

No. Closing.
